### ISSUE TITLE
Update BIDMach on mercury

### ISSUE THREAD

**Issue by davclark** [berkeley-dsc/destress#10]
Update includes a data spec file that will enable full download of all sample data.

**Comment by cdschillaci** [comment]
When did you last update? When I try to run BIDMach I get 

> Loading /opt/BIDMach_1.0.0-full-linux-x86_64/lib/bidmach_init.scala...
> import BIDMat.{CMat, CSMat, DMat, Dict, FMat, FND, GMat, GDMat, GIMat, GLMat, GSMat, GSDMat, HMat, IDict, Image, IMat, LMat, Mat, SMat, SBMat, SDMat}
> import BIDMat.MatFunctions._
> import BIDMat.SciFunctions._
> import BIDMat.Solvers._
> import BIDMat.Plotting._
> import BIDMach.Learner
> import BIDMach.models.{DNN, FM, GLM, KMeans, KMeansw, LDA, LDAgibbs, Model, NMF, SFA}
> import BIDMach.datasources.{DataSource, MatDS, FilesDS, SFilesDS}
> import BIDMach.mixins.{CosineSim, Perplexity, Top, L1Regularizer, L2Regularizer}
> import BIDMach.updaters.{ADAGrad, Batch, BatchNorm, IncMult, IncNorm, Telescoping}
> import BIDMach.causal.IPTW
> Cant find native CPU libraries
> Cant find native HDF5 library
> Couldnt load CUDA runtime

**Comment by davclark** [comment]
Sorry about that - you should use `./bidmach2` - I was just looking to figure out the differences between the two scripts, and ./bidmach2 has appropriate settings for the installation on mercury.

Should we put this on the wiki?

**Comment by davclark** [comment]
I just renamed the old `bidmach` and made a symlink to bidmach2.
