### ISSUE TITLE
Give access to Lucene implementation on stout

### ISSUE THREAD

**Issue by peparedes** [berkeley-dsc/destress#12]
John - how could we provide access to at least some folks working on queries to the lucene search implementation on the livejournal data on stout?

**Comment by davclark** [comment]
Hey @peparedes, if you "@-mention" people, it will automatically show up in their git inbox (and maybe trigger an email, depending on settings). John hasn't accepted his invite to this repo, though - so maybe we should ask / remind him to.

But more importantly, is this still necessary - or are we able to simply use Lucene with the index files I copied to mercury?

**Comment by peparedes** [comment]
Seems we could use the I deres you copied...  Gene is looking into it.

John offered to make it work as well...  Buy yes,  he needs to accept
first.

P

**Comment by geneyoo** [comment]
I'm looking into it right now -- I'll let you know if I find success into using the indices (it looks likely, at least for the original format). But, another thing I'm worried about is the new concatenated files that we would be using? Since pierre now combined the files... the indices for the new searches will not be valid.

**Comment by davclark** [comment]
It's not clear that we need to be looking at the same files for all cases... I think it's fine for now if the lucene index returns the smaller / older files.

**Comment by geneyoo** [comment]
Just tested a few searches using some queries with the copied /index/ directory, and it seems valid/functional. It looks like we won't need to re-create indices.

**Comment by peparedes** [comment]
Excellent!

Good job!

P

**Comment by coryschillaci** [comment]
Can we close this issue? Seems like the remaining work is in #11 .
