### ISSUE TITLE
Run xmltweet on the data set

### ISSUE THREAD

**Issue by cdschillaci** [berkeley-dsc/destress#15]
@davclark Do we have disk space to run the tokenizer at this point? I uploaded a script  into process_data/tokenize_files.sh which can be run with minimal changes (just select the input and output folders).

**Comment by davclark** [comment]
What's the ratio of input size to output size?

**Comment by cdschillaci** [comment]
It's pretty close to 1:1 actually, so I guess definitely not enough space. Here's an example.

Raw:

> -rw-rw-r-- 1 schillaci schillaci 1.8G Mar  3 19:37 ba.xml

Tokenized:

> -rw-rw-r-- 1 schillaci schillaci 1.6G Mar  3 19:38 ba.xml.imat
> -rw-rw-r-- 1 schillaci schillaci  27M Mar  3 19:38 ba_dict.imat
> -rw-rw-r-- 1 schillaci schillaci 134M Mar  3 19:38 ba_dict.sbmat

**Comment by davclark** [comment]
Yeah - we could do a subset, but we are definitely lean on space. There is
a 3TB drive coming via FedEx...

D

**Comment by anasrferreira** [comment]
@davclark new xmltweet.exe is now compiled and moved to /var/local/destress/scripts/
@cdschillaci tokenize_files.sh has been updated with new xmltweet.exe path.

**Comment by cdschillaci** [comment]
@anasrferreira Is this your version or the new official BIDMach version?

**Comment by anasrferreira** [comment]
This is from the most recent BIDMach pull onto my mercury account.
BIDMach doesn't come with xmltweet.exe. It needs to be compiled.

**Comment by peparedes** [comment]
Actually I think it does... I think it is in BIDMach/bin

P

**Comment by davclark** [comment]
I announced this on Slack - but just so we're clear, there's 2TB now on /var/local

**Comment by coryschillaci** [comment]
Running xmltweet on everything now.

**Comment by davclark** [comment]
Whee!

**Comment by coryschillaci** [comment]
Ran in 115 minutes. The dictionaries etc. have been output to `/var/local/destress/tokenized`

**Comment by peparedes** [comment]
Awesome!

P
