### ISSUE TITLE
Create a BIDMat dict for moodids

### ISSUE THREAD

**Issue by coryschillaci** [berkeley-dsc/destress#29]
Can someone generate a BIDMat dict which maps the moodids to their strings? Should be 135 entries. Zero should correspond to "not specified" in someway, while 50 and 94 are not used by LiveJournal,  @anasrferreira or @lambdaloop willing to volunteer?

**Comment by anasrferreira** [comment]
Done. See sbmat file: `/var/local/destress/moodDict.sbmat`
